global:
  scrape_interval: 5s

scrape_configs:
  - job_name: ingest
    static_configs:
      - targets: ["ingest:4301"]
  - job_name: observe
    static_configs:
      - targets: ["observe:4302"]
  - job_name: diagnose
    static_configs:
      - targets: ["diagnose:4303"]
